### ISSUE TITLE
Invalid plugin yml error

### ISSUE THREAD

**Issue by simonlayfield** [MattCzyr/EnderMail#4]
I'm running 1.15.2 and get the following error when restarting:

```
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:159) ~[patched_1.15.2.jar:git-Paper-145]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.15.2.jar:git-Paper-145]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-145]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-145]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
```
Not sure why others who have downloaded it don't get this issue (?)

Apologies if this is something at my end - I have limited experience with mods.

**Comment by MattCzyr** [comment]
This log implies that you're trying to load the mod with Bukkit. Is that true? This is a mod, not a plugin, so you should be using Forge to load it.

**Comment by simonlayfield** [comment]
Ah right I see - yeah I think so.

Ok thanks, and apologies for raising.
